import { Card, CardContent } from "@/components/ui/card";
import {
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger,
} from "@/components/ui/collapsible";
import { Text } from "@/components/ui/misc";
import { ChevronDown } from "lucide-react";

export default function TermsAndConditionsPage() {
  const sections = [
    {
      title: "Definition of Terms",
      content:
        "For purposes of these Terms and Conditions, the following terms shall have the meanings set forth in this Section: \"System\" refers to the School Employee Management System and its related modules, pages, and services; \"School\" refers to the institution and its duly authorized offices, administrators, and representatives; \"User\" refers to any person granted access credentials, whether as administrator, staff, or other authorized personnel.\n\n\"Account\" means the registered access identity assigned to a User, including login credentials and associated role permissions; \"Data\" means all records, entries, files, and information submitted to, generated by, or stored in the System, including personal and employment-related information; \"Authorized Use\" means use strictly within assigned role permissions and for legitimate school functions.\n\nAny capitalized term not expressly defined in this Section shall be interpreted according to its ordinary administrative, technical, or legal meaning in context, and, where applicable, in accordance with school policy and governing law.",
    },
    {
      title: "Acceptance of Terms",
      content:
        "By accessing, browsing, registering for, or otherwise using this School Employee Management System (the \"System\"), you acknowledge that you have read, understood, and agreed to be bound by these Terms and Conditions, as may be amended from time to time.\n\nIf you do not agree to these Terms and Conditions in full, you must immediately discontinue use of the System. Continued use of the System after publication of updates constitutes your acceptance of the revised terms.\n\nThese Terms and Conditions operate together with applicable school policies, internal administrative guidelines, and governing laws and regulations. In the event of conflict, mandatory legal requirements and official school directives shall prevail.",
    },
    {
      title: "Authorized Use",
      content:
        "Access to the System is strictly limited to users who have been duly authorized by the school administration and granted credentials under a defined role. You may access only the modules, records, and operations expressly permitted for your assigned privileges.\n\nYou agree not to circumvent, disable, or interfere with access controls, authentication measures, audit safeguards, or technical restrictions implemented by the System. Any attempt to access accounts, records, features, or administrative functions beyond your authorization is prohibited.\n\nUse of shared, borrowed, or unauthorized credentials is likewise prohibited. You remain responsible for all actions performed through your account unless and until the school has been notified through official channels of a confirmed compromise.",
    },
    {
      title: "Data Responsibility",
      content:
        "Users are required to enter, update, and maintain accurate, complete, and timely data in the System to support school operations, reporting integrity, and lawful record-keeping. Knowingly submitting false, misleading, or materially incomplete information is prohibited.\n\nBecause the System may contain sensitive employee and institutional data, users must observe strict confidentiality and exercise due care in collection, encoding, review, sharing, and storage of records. Access to information must be limited to legitimate school purposes and only to the extent required by official duty.\n\nYou agree to comply with applicable privacy and data protection requirements, including internal retention and disclosure rules, and to cooperate in correction, audit, or verification procedures initiated by authorized administrators.",
    },
    {
      title: "Security and Access",
      content:
        "You are solely responsible for maintaining the confidentiality and security of your login credentials, including username, password, authentication tokens, and device access used to reach the System. Credentials must not be disclosed, reused insecurely, or stored in an exposed manner.\n\nYou must implement reasonable security practices, including use of strong passwords, secure devices, timely software updates, and immediate sign-out from shared or public terminals. Where applicable, you must follow additional security instructions issued by the school.\n\nAny suspected unauthorized access, credential compromise, suspicious account behavior, or data incident must be reported immediately through designated school administrative or technical support channels. The school may suspend or restrict access, with or without prior notice, to protect system integrity and institutional data.",
    },
    {
      title: "Service Changes",
      content:
        "The school reserves the right, at its sole discretion and without liability, to modify, enhance, limit, suspend, or discontinue any part of the System, including features, workflows, access levels, integrations, and technical requirements, whether temporarily or permanently.\n\nSuch changes may be implemented for operational, security, maintenance, compliance, policy, or administrative reasons. The school may also perform scheduled or emergency downtime and may not always be able to provide advance notice in urgent cases.\n\nWhere reasonable, notices of material changes may be issued through official channels. Your continued use of the System following implementation of changes constitutes acceptance of the updated service configuration and applicable terms.",
    },
    {
      title: "Contact Information",
      content:
        "For questions, clarifications, incident reports, requests for record correction, or concerns regarding interpretation and application of these Terms and Conditions, you must contact the school through its officially designated administrative or support channels.\n\nAll communications relating to legal, policy, account access, and data concerns should include sufficient detail to allow verification and timely response. The school may require identity confirmation and supporting information before processing certain requests.\n\nOfficial responses, advisories, and directives issued by authorized school representatives shall govern the operational handling of concerns under these Terms and Conditions.",
    },
    {
      title: "Data Privacy and Protection",
      content:
        "The System may collect and process personal, employment, and administrative information solely for legitimate school operations, records administration, reporting, and authorized personnel management functions.\n\nThe School does not sell personal data collected through the System to third parties. Any disclosure or sharing of data shall be limited to lawful, policy-compliant, and operationally necessary purposes, and only with appropriately authorized parties and safeguards.\n\nAll Users are required to handle personal data responsibly and in accordance with applicable privacy requirements, internal policies, confidentiality obligations, and security procedures, including minimum-necessary access and proper retention practices.",
    },
    {
      title: "Disclaimer and Limitation of Liability",
      content:
        "The System is provided on an \"as is\" and \"as available\" basis, and the School makes no representation or warranty of uninterrupted availability, absolute accuracy, or suitability for any specific purpose, except where required by law.\n\nTo the fullest extent permitted under applicable law, neither the School nor the development team shall be liable for any direct, indirect, incidental, consequential, special, or exemplary damages arising from or related to use of, inability to use, misuse of, or reliance upon the System, including data loss, delay, downtime, or operational disruption.\n\nNothing in this provision shall exclude liability where exclusion is prohibited by governing law. Users remain responsible for lawful use, proper verification of critical records, and compliance with official processes.",
    },
    {
      title: "Intellectual Property",
      content:
        "All rights, title, and interest in the System, including its software, interface design, workflows, content structure, and related documentation, are owned by or lawfully licensed to the School and/or their respective rights holders.\n\nExcept as expressly permitted in writing, Users may not reproduce, distribute, modify, reverse engineer, decompile, republish, or create derivative works from any part of the System.\n\nUse of the System grants only a limited, revocable, non-transferable right of access for authorized school purposes and does not transfer ownership of intellectual property.",
    },
    {
      title: "Prohibited Conduct",
      content:
        "Users shall not use the System for unlawful, fraudulent, abusive, or unauthorized purposes, including unauthorized data extraction, tampering, credential sharing, malware distribution, or attempts to bypass technical or administrative controls.\n\nUsers shall not impersonate other individuals, alter audit trails, submit knowingly false records, or perform actions that could compromise data integrity, confidentiality, or service availability.\n\nViolations may result in immediate account restriction, suspension, termination, disciplinary action, and referral to proper authorities, as appropriate.",
    },
    {
      title: "Suspension and Termination",
      content:
        "The School reserves the right to suspend, restrict, or terminate access to the System, in whole or in part, when necessary for security, compliance, operational continuity, policy enforcement, or disciplinary reasons.\n\nSuch action may be taken with or without prior notice where immediate intervention is reasonably required to protect users, records, infrastructure, or institutional interests.\n\nUpon suspension or termination, the affected User must immediately cease access and use of the System, and relevant records may be retained for audit, compliance, and legal purposes.",
    },
    {
      title: "Governing Law and Severability",
      content:
        "These Terms and Conditions shall be governed by and interpreted in accordance with applicable laws, regulations, and valid school policies. Disputes should first be raised through official school administrative channels for good-faith resolution.\n\nIf any provision of these Terms is determined invalid or unenforceable by a competent authority, that provision shall be interpreted to the maximum lawful extent, and the remaining provisions shall remain effective and enforceable.\n\nFailure by the School to enforce any provision at any time shall not be deemed a waiver of its right to enforce that or any other provision in the future.",
    },
  ];

  return (
    <main className="relative min-h-full overflow-hidden p-4 md:p-8">
      <div className="pointer-events-none absolute inset-0">
        <div className="absolute -top-24 left-14 h-64 w-64 rounded-full bg-primary/10 blur-3xl" />
        <div className="absolute -bottom-16 right-10 h-56 w-56 rounded-full bg-accent/20 blur-3xl" />
      </div>

      <section className="relative mx-auto w-full max-w-5xl space-y-5">
        <Card className="border-border bg-card/95">
          <CardContent className="space-y-2 p-6 md:p-8">
            <Text className="inline-flex rounded-full border border-primary/30 bg-primary/10 px-3 py-1 text-xs font-semibold uppercase tracking-wide text-primary">
              Legal
            </Text>
            <h1 className="text-2xl font-semibold leading-tight md:text-4xl">
              Terms and Conditions
            </h1>
            <Text className="text-muted-foreground">
              Effective Date: {new Date().toLocaleDateString()}
            </Text>
          </CardContent>
        </Card>

        <Card className="border-border bg-card">
          <CardContent className="space-y-4 p-6 md:p-8">
            {sections.map((section, index) => (
              <Collapsible
                key={section.title}
                className="rounded-lg border border-border/70"
              >
                <CollapsibleTrigger className="group flex w-full items-center justify-between gap-3 px-4 py-3 text-left">
                  <Text weight="semibold">{index}. {section.title}</Text>
                  <ChevronDown className="size-4 shrink-0 text-muted-foreground transition-transform group-data-[state=open]:rotate-180" />
                </CollapsibleTrigger>
                <CollapsibleContent className="px-4 pb-4">
                  <Text
                    size="sm"
                    className="whitespace-pre-line text-muted-foreground"
                  >
                    {section.content}
                  </Text>
                </CollapsibleContent>
              </Collapsible>
            ))}
          </CardContent>
        </Card>
      </section>
    </main>
  );
}
